// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihvsbnknjgnnwaynjmgg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlodnNibmtuamdubndheW5qbWdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MTQzNjEsImV4cCI6MjA3Mzk5MDM2MX0.cDrfu8HtIGYYbuGRZm48eolsHQa-2p02_nLG9XZjgmQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
    }
});
